# Use root/example as user/password credentials
version: '3.1'

services:

  # cruise:
  #   image: cruise
  #   build: .
  #   ports:
  #     - 8080:8080
  #   environment: 
  #     -JAVA_OPTS
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 7080:8080